Migrate elements to UMD version
akash-network/console pull request #317
Opened 2024-08-17 05:55 UTC by siddharthborderwala

- Fixes the elements crash
- Migrate to using elements via UMD - read about differences and benefits [here](https://leapwallet.notion.site/Integrating-Elements-via-UMD-module-e2234cec91bf48a5a6d304a4bf60d870)
- Use elements UMD types package for TS support

2024-08-17 06:19 UTC, siddharthborderwala commented
@baktun14 I have migrated elements to usage via CDN instead of using as an NPM package. It fixes the crash that's happening due to a Nextjs SWC minification issue.

Some of the other benefits of the UMD build are
- Bundle size of your dApp decreases
- No build/bundling for elements needed

2024-08-21 13:53 UTC, baktun14 commented
The leap wallet styling overrides the app styling

![image](https://github.com/user-attachments/assets/76622d0f-4e4c-411f-ad20-09a8a7a358f1)
![image](https://github.com/user-attachments/assets/450d193c-763f-49d5-858d-b4c1c1bcb6ee)

2024-08-22 07:13 UTC, siddharthborderwala commented
@baktun14 thank you for making a note of this. It's a bug with the stylesheet for version 1.4.1. We're releasing version 1.4.2 today/tomorrow which will have the fix for this. Will update then.

2024-08-23 07:01 UTC, siddharthborderwala commented
Hi @baktun14 I have fixed the issue with the stylesheets. It won't affect the rest of the app.

2024-08-27 14:55 UTC, baktun14 commented
> Hi @baktun14 I have fixed the issue with the stylesheets. It won't affect the rest of the app.

The styling issues seem to have been fixed. 👍

2024-09-06 14:24 UTC, baktun14 requested changes

2024-09-06 14:24 UTC, baktun14 commented on apps/deploy-web/src/pages/_document.tsx
> +        <script defer src="https://unpkg.com/@leapwallet/elements@1.4.2/dist/umd/main.js" />
I'm not a big fan of importing this globally when we only need it in the get started page.

2024-09-06 14:24 UTC, baktun14 commented on apps/deploy-web/src/pages/_document.tsx
> +        <script defer src="https://unpkg.com/@leapwallet/elements@1.4.2/dist/umd/main.js" />
@siddharthborderwala Would it possible to import these dynamically?

2024-09-11 20:44 UTC, baktun14 commented on apps/deploy-web/src/pages/_document.tsx
> +        <script defer src="https://unpkg.com/@leapwallet/elements@1.4.2/dist/umd/main.js" />
Any update on this? @siddharthborderwala

2024-09-12 06:39 UTC, siddharthborderwala commented on apps/deploy-web/src/pages/_document.tsx
> +        <script defer src="https://unpkg.com/@leapwallet/elements@1.4.2/dist/umd/main.js" />
@baktun14 will update this and push changes

2024-09-12 06:55 UTC, siddharthborderwala commented on apps/deploy-web/src/pages/_document.tsx
> +        <script defer src="https://unpkg.com/@leapwallet/elements@1.4.2/dist/umd/main.js" />
@baktun14 I've made the required changes. Now the elements related CSS and JS will be loaded only on the `/get-started` page.

2024-09-16 16:32 UTC, ygrishajev approved these changes

2024-09-16 17:06 UTC, baktun14 commented
@siddharthborderwala Hey, I rebased and fixed some issues, but for some reason the @leapwallet/elements package is still a dependency of the types packages and it messed up our CI...

https://github.com/akash-network/console/actions/runs/10888482586/job/30213077526?pr=317

2024-09-16 18:05 UTC, baktun14 approved these changes

2024-09-16 18:08 UTC, merged