fix(env): convert all env vars to SCREAMING_CASE from camelCase
akash-network/console pull request #335
Opened 2024-08-23 00:35 UTC by hiroyukikumazawa

2024-08-23 00:37 UTC, hiroyukikumazawa commented
refs: #310

2024-08-26 09:34 UTC, ygrishajev commented
hey @hiroyukikumazawa looks like a bunch of envs are not updated here https://github.com/akash-network/console/blob/main/packages/database/chainDefinitions.ts
Would be real nice if you kindly could check if the apps are at least starting without errors.

Note: I found it's only `ActiveChain` and it only affects indexer. @Redm4x @baktun14 are other used at all?

2024-08-26 12:05 UTC, hiroyukikumazawa commented
> hey @hiroyukikumazawa looks like a bunch of envs are not updated here https://github.com/akash-network/console/blob/main/packages/database/chainDefinitions.ts Would be real nice if you kindly could check if the apps are at least starting without errors.
> 
> Note: I found it's only `ActiveChain` and it only affects indexer. @Redm4x @baktun14 are other used at all?

Ok, I see
And the apps projects are working correctly with this updates.
What about your side?

2024-08-26 14:26 UTC, ygrishajev commented
> > hey @hiroyukikumazawa looks like a bunch of envs are not updated here https://github.com/akash-network/console/blob/main/packages/database/chainDefinitions.ts Would be real nice if you kindly could check if the apps are at least starting without errors.
> > Note: I found it's only `ActiveChain` and it only affects indexer. @Redm4x @baktun14 are other used at all?
> 
> Ok, I see And the apps projects are working correctly with this updates. What about your side? @ygrishajev

@hiroyukikumazawa yea, that should do, thanks! I'd still like @Redm4x or @baktun14 to check this out too

2024-08-29 14:22 UTC, baktun14 commented
> hey @hiroyukikumazawa looks like a bunch of envs are not updated here https://github.com/akash-network/console/blob/main/packages/database/chainDefinitions.ts Would be real nice if you kindly could check if the apps are at least starting without errors.
> 
> Note: I found it's only `ActiveChain` and it only affects indexer. @Redm4x @baktun14 are other used at all?

We only need akash related env var in this file. Others are to run the indexer for other chains, which we don't care for console.

2024-08-29 15:53 UTC, baktun14 approved these changes

2024-08-29 15:57 UTC, Redm4x approved these changes

2024-09-02 09:39 UTC, ygrishajev commented
Hey @hiroyukikumazawa pls rebase and I'll deploy this to staging so everyone can test. Then we'll merge

2024-09-09 15:42 UTC, ygrishajev commented
@hiroyukikumazawa any chance you could rebase soon?

2024-09-09 18:37 UTC, hiroyukikumazawa commented
> We only need akash related env var in this file. Others are to run the indexer for other chains, which we don't care for console

I will rebase now

2024-09-09 18:46 UTC, ygrishajev commented
@hiroyukikumazawa  I've done relevant changes in deployment-web last week, which change the location of configs and also renames vars to uppercase. Please accept main changes in case of conflicts.

Ref https://github.com/akash-network/console/pull/355

2024-09-09 18:49 UTC, hiroyukikumazawa commented
> @hiroyukikumazawa I've done relevant changes in deploy-web last week, which change the location of configs and also renames vars to uppercase. Please accept 'main' changes in case of conflicts.

ok

2024-09-09 19:20 UTC, hiroyukikumazawa commented
@ygrishajev please review again

2024-09-10 07:10 UTC, ygrishajev commented
@hiroyukikumazawa I see another conflict, would you handle that?

2024-09-10 08:03 UTC, hiroyukikumazawa commented
@ygrishajev please check again

2024-09-10 08:24 UTC, ygrishajev commented
@hiroyukikumazawa thanks a bunch! So I've deployed api to our beta and have indexer running locally. I'd like @Redm4x and @baktun14 to verify it once again and merge this.

I'm going to squash commits on merge but you're welcome to do so yourself in the branch if you like so.


Locally I have these vars set:
```
ACTIVE_CHAIN=akashSandbox
AKASH_DATABASE_CS=postgres://postgres:password@db:5432/console-akash-sandbox
ActiveChain=akashSandbox
``` 
<img width="988" alt="image" src="https://github.com/user-attachments/assets/36b01783-ffa4-4cb0-b482-fd1ef9eaa5fa">

2024-09-10 08:31 UTC, hiroyukikumazawa commented
> ActiveChain

was `ActiveChain=akashSandbox` need in indexer?

2024-09-10 08:35 UTC, ygrishajev commented
> > ActiveChain
> 
> @ygrishajev was `ActiveChain=akashSandbox` needed in indexer?

oh, indeed I found a bunch of them used
<img width="1553" alt="image" src="https://github.com/user-attachments/assets/adf8920d-ce20-4d9d-8b2d-e64c3fbe6a2e">

2024-09-10 08:46 UTC, hiroyukikumazawa commented
I thought `activeChain` is not a env var. 
Instead, `ActiveChain` is in the readme.
And in my local, without ActiveChain env var it's working.

2024-09-10 08:47 UTC, hiroyukikumazawa commented
@ygrishajev done squash commit

2024-09-10 08:53 UTC, ygrishajev commented
> @ygrishajev I thought `activeChain` is not a env var. Instead, `ActiveChain` is in the readme. And in my local, without ActiveChain env var it's working.

@hiroyukikumazawa https://github.com/akash-network/console/pull/335/files#diff-a7b12b4516cdcf3f8b1898a997e54d3b4a328a14bb80aecf30e2e23734e3a3a8R412

2024-09-10 09:34 UTC, hiroyukikumazawa commented
> > @ygrishajev I thought `activeChain` is not a env var. Instead, `ActiveChain` is in the readme. And in my local, without ActiveChain env var it's working.
> 
> @hiroyukikumazawa https://github.com/akash-network/console/pull/335/files#diff-a7b12b4516cdcf3f8b1898a997e54d3b4a328a14bb80aecf30e2e23734e3a3a8R412

wdym?

2024-09-10 14:04 UTC, Redm4x requested changes

2024-09-10 14:04 UTC, Redm4x commented on apps/api/src/utils/env.ts
>      ProviderUptimeGracePeriodMinutes: z
`ProviderUptimeGracePeriodMinutes` was missed

2024-09-10 14:14 UTC, hiroyukikumazawa commented on apps/api/src/utils/env.ts
>      ProviderUptimeGracePeriodMinutes: z
ok, will update now

2024-09-10 14:25 UTC, hiroyukikumazawa commented on apps/api/src/utils/env.ts
>      ProviderUptimeGracePeriodMinutes: z
please check again @Redm4x

2024-09-11 19:27 UTC, Redm4x approved these changes

2024-09-11 19:34 UTC, ygrishajev approved these changes

2024-09-11 21:27 UTC, merged