Feature to improve stats app charts
akash-network/console pull request #347
Opened 2024-09-02 16:52 UTC by forbesus

refs #298

2024-09-02 17:05 UTC, forbesus commented
hello @baktun14 
I have done #298 would you check this pr?

2024-09-03 18:06 UTC, baktun14 commented
Hey @forbesus I just tested and it works great! I have a few modifications requirements:
- Would it possible to remove the TV logo?
- When you switch between 7d 1M ALL, the zoom works but it only includes the data of that range so when you zoom out in 7d/1M, it doesn't really work. There's some logic that slices the data coming from props `rangedData`
- Would it possible to have less padding by default at the top and bottom of the chart?
![image](https://github.com/user-attachments/assets/2b2faae2-ace1-477b-8745-e314fbd5b16b)
- Would it be possible to have the same unit as the current value in the right axis labels? 
![image](https://github.com/user-attachments/assets/8a356ee3-3c4b-4d3c-be80-81354fa87582)
![image](https://github.com/user-attachments/assets/5c38ef36-dfbe-44a3-871b-f9a7cec431b4)

Thanks for your contribution!

2024-09-03 18:12 UTC, baktun14 requested changes

2024-09-03 18:12 UTC, baktun14 commented on apps/stats-web/package.json
> +    "moment": "^2.30.1",
Please remove moment and use `data-fns`, that's the library we use in other projects for time based functions.

2024-09-03 18:12 UTC, baktun14 commented on apps/stats-web/src/components/graph/Graph.tsx
> +        value: _snapshot.value
There was a unitFn called in the previous code `y: roundDecimal(snapshotMetadata.unitFn(_snapshot.value).value)` which is probably why the values don't match.

2024-09-05 11:39 UTC, forbesus commented
Hello @baktun14 i fixed and completed
Would you check again?

2024-09-05 15:20 UTC, baktun14 commented
@forbesus Great, I will check today.

2024-09-09 19:35 UTC, baktun14 commented
@forbesus  There's a bug when changing the time range, it duplicates the graph. I'm investigating it.
![image](https://github.com/user-attachments/assets/db78e953-3ada-4625-9073-eb3f39dfe957)

2024-09-09 19:48 UTC, forbesus commented
Hello @baktun14 I checked it but I have a question
Did you check it after removing browser cache?

2024-09-09 19:53 UTC, baktun14 commented
> Hello @baktun14 I checked it but I have a question Did you check it after removing browser cache?

It doesn't change the behavior for me

2024-09-09 20:45 UTC, forbesus commented
Hello @baktun14 
I fixed that problem 
Would you check again?

2024-09-09 21:06 UTC, baktun14 commented
@forbesus It works great!

2024-09-09 21:41 UTC, baktun14 approved these changes

2024-09-09 21:42 UTC, baktun14 commented
Great work @forbesus ! I fixed a resize issue and theme issue, but otherwise all is good to merge.

2024-09-09 21:43 UTC, forbesus commented
Thank you @baktun14

2024-09-09 23:51 UTC, merged