feat:update react query version
akash-network/console pull request #350
Opened 2024-09-04 12:06 UTC by ShinySyntax

2024-09-04 16:00 UTC, baktun14 requested changes

2024-09-04 16:00 UTC, baktun14 commented on apps/deploy-web/src/context/SettingsProvider/SettingsProviderContext.tsx
> +};
What happened here? This code is duplicated.

2024-09-04 16:00 UTC, baktun14 commented on apps/provider-console/src/context/SettingsProvider/SettingsProviderContext.tsx
> +        }
Please undo these changes. This will probably be refactored anyways since the provider console project is still under construction.

2024-09-04 16:04 UTC, ShinySyntax commented on apps/deploy-web/src/context/SettingsProvider/SettingsProviderContext.tsx
> +};
I will resolve it

2024-09-04 16:10 UTC, ShinySyntax commented on apps/provider-console/src/context/SettingsProvider/SettingsProviderContext.tsx
> +        }
I fixed it.

2024-09-05 06:26 UTC, ShinySyntax commented on apps/deploy-web/src/context/SettingsProvider/SettingsProviderContext.tsx
> +};
I resolved it.
Plz check it.

2024-09-05 06:26 UTC, ShinySyntax commented
Hello, @baktun14 
I have fixed all errors.
Plz check.

2024-09-05 10:02 UTC, closed without merging

2024-09-05 15:19 UTC, baktun14 commented
Hey @ShinySyntax any reason you closed this pr?

2024-09-05 15:42 UTC, ShinySyntax commented
Sure, I found some error.
So, I am fixing now.
I will create new PR.

2024-09-05 18:14 UTC, baktun14 commented
@ShinySyntax  You can just update the pr instead of closing and opening a new one.

2024-09-05 18:23 UTC, ShinySyntax commented
Got it.
Thanks for your reaching out.