feat: update react query version
akash-network/console pull request #356
Opened 2024-09-05 16:06 UTC by ShinySyntax

2024-09-05 22:14 UTC, baktun14 requested changes
I think you need to rebase your branch/fork because some changes are being unmade by your pr.

2024-09-05 22:14 UTC, baktun14 commented on apps/api/src/core/services/hono-error-handler/hono-error-handler.service.ts
> +    const id = this.sentry.captureEvent(await this.getSentryEvent(error, c));
Any reason why you removed the try catch?

2024-09-05 22:14 UTC, baktun14 commented on apps/api/src/core/services/hono-error-handler/hono-error-handler.service.ts
> +      body: await c.req.json()
Same question here?

2024-09-05 22:14 UTC, baktun14 commented on apps/api/src/core/services/hono-error-handler/hono-error-handler.service.ts
> -  private async getSentryEventRequestBody<E extends Env = any>(c: Context<E>) {
?

2024-09-05 23:39 UTC, ShinySyntax commented on apps/api/src/core/services/hono-error-handler/hono-error-handler.service.ts
> +    const id = this.sentry.captureEvent(await this.getSentryEvent(error, c));
I added.

2024-09-05 23:39 UTC, ShinySyntax commented on apps/api/src/core/services/hono-error-handler/hono-error-handler.service.ts
> -  private async getSentryEventRequestBody<E extends Env = any>(c: Context<E>) {
I added.

2024-09-05 23:40 UTC, ShinySyntax commented
I fixed all

2024-09-11 20:40 UTC, baktun14 requested changes

2024-09-11 20:40 UTC, baktun14 commented on apps/api/package.json
> +    "@chain-registry/assets": "^0.7.1",
Why change the version?

2024-09-11 20:40 UTC, baktun14 commented on apps/api/src/utils/coin.ts
>  import { asset_lists } from "@chain-registry/assets";
Why change this file?

2024-09-11 20:40 UTC, baktun14 commented on apps/api/src/routes/v1/deployments/byOwnerDseq.ts
>          description: "Owner's Address",
why change this file?

2024-09-11 20:40 UTC, baktun14 commented on apps/api/src/routes/internal/leasesDuration.ts
>        owner: z.string().openapi({ example: openApiExampleAddress })
why change this file?

2024-09-11 20:40 UTC, baktun14 commented on apps/deploy-web/package.json
> +  "version": "2.12.0",
?

2024-09-11 20:40 UTC, baktun14 commented on apps/deploy-web/src/components/new-deployment/ManifestEdit.tsx
> +      setEditedManifest(prev => prev.replace(/uakt/g, managedDenom));
Why change this file?

2024-09-11 20:40 UTC, baktun14 commented on apps/provider-console/src/context/SettingsProvider/SettingsProviderContext.tsx
> +      try {
Why change this file?

2024-09-12 02:40 UTC, closed without merging