feature: Enable Deployment from Git Repositories to Akash Network
akash-network/console pull request #381
Opened 2024-09-21 01:57 UTC by HoomanDgtl

This is a PR that addresses the new feature addition, enabling deployment directly from GitHub, GitLab, or Bitbucket onto the Akash Network.

Issue: https://github.com/akash-network/console/issues/226

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/deployments/DeploymentDetail.tsx
> +  }, [deployment]);
I'm not sure I understand. This code is copied from `ManifestUpdate` into here, so now it runs twice in two components? Is it intended?

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/deployments/ManifestUpdate.tsx
> +  setEditedManifest: Dispatch<React.SetStateAction<string>>;
After thinking a bit further I'm not sure it's a good idea to share state dispatchers. The outer interface on the component should basically do 2 way data binding: either accept input or callbacks for events. Otherwise it's confusing and couples components quite a bit.
Naming matters quite a bit in terms how this component would be developing in the future. I'll put an example for 1 of the props:

```suggestion
  onManifestChange: (value: string) => void;
```

so than on the client it would look like:

```tsx
<ManifestUpdate
   onManifestChange={setEditedManifest}
   {...props}
/>
```

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/deployments/DeploymentDetail.tsx
> +  }, [deployment]);
After inspecting the code a bit more it seems to me that this code was only moved to get access to `editedManifest` to get some other relevant data. Is it so?

If it is, this change seems to be a bit of overhead as you could just expose `onManifestChange` prop as suggested in the comment below.

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/new-deployment/ManifestEdit.tsx
> +  useEffect(() => {
let's do it the same way as it's done in the code above on L92 with `useWhen`, also let's move these two hooks close together

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/new-deployment/ManifestEdit.tsx
> +  const [isRepoDataValidated, setIsRepoDataValidated] = useState(false);
`validated` sounds like data was validated leaving validity question unanswered. `data` may mean many things, I suggest `input` as it's a bit more specific. You're welcome to find even better name if you like.

```suggestion
  const [isRepoInputValid, setIsRepoInputValid] = useState(false);
```

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/new-deployment/TemplateList.tsx
> +          {/* <DeployOptionBox
why commented?

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
quite some exports here are configuration constants which are handled differently in this app. Check out:
https://github.com/akash-network/console/tree/main/apps/deploy-web/src/config
https://github.com/akash-network/console/blob/main/doc/apps-configuration.md

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
helper functions is a bad name. I realise we have some like this but we do not introduce new ones. Please create dedicated service files grouped by their application/domain. There's a services dir in the root of the app which can host such logic.

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +export const PROXY_API_URL_AUTH = "https://proxy-console-github.vercel.app";
unused

2024-10-02 10:33 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +export const ciCdTemplateId = "akash-network-awesome-akash-automatic-deployment-CICD-template";
config constants should be SCREAMING_CASE

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +export function appendEnv(key: string, value: string, isSecret: boolean, setValue: ServiceSetValue, services: ServiceType[]) {
too much arguments, please make it a configuration object. Some random [ref I found](https://stackoverflow.com/questions/2244860/when-a-method-has-too-many-parameters)

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +  setValue("services.0.env", previousEnv);
having a form method and it's internal details breaks separation of concerns. This function cannot be used outside the form context although it's declared far from such context.
I think this should just return a value and values assignment should happen on the client.

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +export const removeInitialUrl = (url?: string) => {
I understand this function gets the last 2 segments of the url provided. However it's going to have different outcomes for different urls obviously. So the name is confusing. What's it intended for?

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +export interface RepoType {
```suggestion
export interface Repo {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +export const isRedeployImage = (yml: string, ciCdYml?: string) => {
CICD is usually used as an acronym of the same case.

```suggestion
export const isRedeployImage = (yml: string, cicdYml?: string) => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
we have all the queries in the root of the app. Having one query per file and named accordingly.

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
> +export const handleLoginBit = () => {
```suggestion
export const loginWithBitBucket = () => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
> +const Bitbucket_API_URL = "https://api.bitbucket.org/2.0";
```suggestion
const BITBUCKET_API_URL = "https://api.bitbucket.org/2.0";
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
> +export const useFetchRefreshBitToken = () => {
```suggestion
export const useBitBucketTokenRefresh = () => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
I think this was already mentioned before by @baktun14. This code has quite some code related to http requests. We extract it into a class based services which expose specific typed methods. You may find some examples [here](https://github.com/akash-network/console/tree/73ff83843947c16a75085b7d7e2ddcead49bc67a/apps/deploy-web/src/services)

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
> +      router.replace(
it's highly unexpected to manage routing an a hook that's only supposed to do a query.

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/github-queries.ts
> +export const handleLogin = () => {
```suggestion
export const loginWithGitHub = () => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/github-queries.ts
> +export const handleReLogin = () => {
```suggestion
export const reLoginWithGitHub = () => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/github-queries.ts
> +        console.log("bad credentials");
who is this intended for?

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/gitlab-queries.ts
> +export const handleGitLabLogin = () => {
```suggestion
export const loginWithGitLab = () => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/RemoteDeployUpdate.tsx
> +  const [, setIsInit] = useState(false);
why is such state needed if it's value is unused?

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/RemoteDeployUpdate.tsx
> +  useEffect(() => {
```suggestion

  useEffect(() => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/Rollback.tsx
> +    services?.[0]?.env?.find(e => e.key === protectedEnvironmentVariables.BRANCH_NAME)?.value
please extract this and the other ones above into a properly named var.

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/Rollback.tsx
> +  if (data && data?.length > 0) {
```suggestion
  if (data?.length > 0) {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/Rollback.tsx
> +  let commits: RollBackType[] | null = null;
wrap into `useMemo`

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/RollbackModal.tsx
> +  useEffect(() => {
```suggestion

  useEffect(() => {
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/RollbackModal.tsx
> +  const [value, setValue] = useState<string>("");
which value is this?

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/remote-deploy/update/RollbackModal.tsx
> +const RollbackModal = ({ data, control }: { data?: RollBackType[] | null; control: Control<SdlBuilderFormValuesType> }) => {
what is this data?

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/sdl/EnvFormModal.tsx
> +    if (_envs.length === 0 || (isRemoteDeployEnvHidden && _envs.filter(e => !(e?.key?.trim() in protectedEnvironmentVariables)).length === 0 && !update)) {
pls create some vars here

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/sdl/EnvFormModal.tsx
> +          ?.filter(e => !isRemoteDeployEnvHidden || !(e?.key?.trim() in protectedEnvironmentVariables))
extract this to a var

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/sdl/EnvVarList.tsx
> +  const currentEnvs = currentService.env?.filter(e => !isRemoteDeployEnvHidden || !(e?.key?.trim() in protectedEnvironmentVariables));
why is it being trimmed everywhere? Can it be trimmed somewhere around the source?

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/sdl/EnvVarList.tsx
> +      {(currentEnvs?.length || 0) > 0 ? (
this should be sufficient. unless I'm missing smth
```suggestion
      {currentEnvs?.length ? (
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/components/sdl/EnvVarList.tsx
> +        currentEnvs?.map((e, i) => (
```suggestion
        currentEnvs.map((e, i) => (
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/hooks/useRemoteDeployFramework.tsx
> +  const [data, setData] = useState<PackageJson | null>(null);
```suggestion
  const [packageJson, setPackageJson] = useState<PackageJson | null>(null);
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/hooks/useRemoteDeployFramework.tsx
> +const useRemoteDeployFramework = ({
I think it's better to remove dep on the form here, pass repo url and other values from envs and resolve with a framework. This would make this hook more reusable and maintainable

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/pages/api/bitbucket/authenticate.ts
> +const BITBUCKET_CLIENT_SECRET: string = process.env.BITBUCKET_CLIENT_SECRET as string;
use server env config

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/pages/api/bitbucket/authenticate.ts
> +    return res.status(400).send("No authorization code provided");
we're trying to unify api responses. to shed some light https://github.com/akash-network/console/blob/main/apps/api/src/core/services/hono-error-handler/hono-error-handler.service.ts

Basically it should replicate `http-errors` serialised error

```suggestion
    return res.status(400).send({ error: 'BadRequestError', message: "No authorization code provided",  });
```

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/services/auth/bitbucket.service.ts
> +      throw new Error("Failed to exchange authorization code for tokens");
what is the point of overriding an error here?

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/services/auth/bitbucket.service.ts
> +      return { access_token, refresh_token };
let's rename to camelCase

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/services/auth/github.service.ts
> +        throw new Error("No access token returned from GitHub");
this error wouldn't make it outside this method

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/types/remoteCommits.ts
did you have a chance to check open source types?
I found this one that seems to do the job https://github.com/octokit/openapi-types.ts/tree/main

2024-10-02 17:28 UTC, ygrishajev commented on apps/deploy-web/src/types/remoteProfile.ts
> +export interface BitProfile {
do you really use all of the fields? perhaps we could remove the unused ones. this way we wouldn't need to maintain them

2024-10-02 19:47 UTC, baktun14 requested changes

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/deployments/DeploymentDetail.tsx
> +  }, [deployment]);
Yea this is strange, please re-use the same code from `ManifestUpdate`.

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/new-deployment/NewDeploymentContainer.tsx
> +    const code = searchParams?.get("code");
Why is this checked in 2 different `useEffect`?

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/new-deployment/NewDeploymentContainer.tsx
> +          setGithub(true);
We already set it above, why is it set again here? Also, the only thing changing here is the url object
```
UrlService.newDeployment({
              ...searchParams,
              step: RouteStep.editDeployment,
              gitProvider: "github"
            })
```
It would be nice to refactor this logic into just setting the object based on the conditions and only have 1 `router.replace(...)`

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/new-deployment/NewDeploymentContainer.tsx
> +  const [github, setGithub] = useState<boolean>(false);
this should be changed to `isGithub` as it's a boolean.

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/new-deployment/SdlBuilder.tsx
> +  github?: boolean;
`isGithub`

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/new-deployment/TemplateList.tsx
> +          {/* <DeployOptionBox
It replaced the hello world template, but this one should be moved in the list of "Staff templates" at the end of the list.

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/helper-functions.ts
> +  setValue("services.0.env", previousEnv);
Agreed.

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
Yes, why was this not refactored as commented before?

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
> +      router.replace(
Yes, this can lead to very unexpected use cases.

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
> +    queryKey: ["userProfile", token.access_token],
We have a `queryKeys` object where we set all the react-query keys, please move all keys over there, as well move all the queries in the queries folder.

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/gitlab-queries.ts
> +      router.replace(
same comment as above

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/update/RemoteDeployUpdate.tsx
> +  console.log(sdlString);
✂️

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/update/RemoteDeployUpdate.tsx
> +  const [, setError] = useState<string | null>(null);
same comment as above

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/sdl/EnvFormModal.tsx
> +  update?: boolean;
```suggestion
  isUpdate?: boolean;
```

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/sdl/EnvVarList.tsx
> +    <FormPaper className={clsx("whitespace-break-spaces break-all", isRemoteDeployEnvHidden && "!bg-card")}>
we use  `cn` not `clsx`

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/components/sdl/EnvVarList.tsx
> +    <FormPaper className={clsx("whitespace-break-spaces break-all", isRemoteDeployEnvHidden && "!bg-card")}>
`import { cn } from "@src/utils/styleUtils";`

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/hooks/useRemoteDeployFramework.tsx
> +  const { isLoading } = usePackageJson(setValueHandler, removeInitialUrl(selected), subFolder);
move all the hooks and state at the top

2024-10-02 19:47 UTC, baktun14 commented on apps/deploy-web/src/pages/api/bitbucket/refresh.ts
> +const BITBUCKET_CLIENT_SECRET: string = process.env.BITBUCKET_CLIENT_SECRET as string;
Same comment as above, everywhere env vars are used.

2024-10-03 07:11 UTC, Chaitanyarai899 commented on apps/deploy-web/src/components/remote-deploy/remote-deploy-api-queries/bit-bucket-queries.ts
Last comment was actaully about apis folder only, we will fix this one asap as well.

2024-10-05 11:31 UTC, dharamveergit commented on apps/deploy-web/src/types/remoteCommits.ts
I searched for open source type for gitlab and bitbucket but they are not available.

2024-10-06 08:58 UTC, ygrishajev commented on apps/deploy-web/package.json
> +    "@octokit/openapi-types": "^22.2.0",
should be dev dep

2024-10-09 16:48 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/RemoteRepositoryDeployManager.tsx
> +  const envVarUpdater = new EnvVarUpdater(services);
I'm not sure we need a class here. Or if we do it should use like this  `useMemo(() => new EnvVarUpdate(services), [services])`

2024-10-09 16:48 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/RemoteRepositoryDeployManager.tsx
> +  const { reLoginWithGithub, loginWithGithub } = new GitHubService();
same thing here

2024-10-09 16:49 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/Repos.tsx
> +  const envVarUpdater = new EnvVarUpdater(services);
`useMemo`

2024-10-09 17:32 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/deployment-configurations/RemoteBuildInstallConfig.tsx
> +  const envVarUpdater = new EnvVarUpdater(services);
`useMemo`

2024-10-09 17:33 UTC, baktun14 commented on apps/deploy-web/src/components/remote-deploy/update/RemoteDeployUpdate.tsx
> +  const envVarUpdater = new EnvVarUpdater(services);
`useMemo`

2024-10-21 13:55 UTC, closed without merging